Repository francoisbaudouin/abstractVM, pull requests merged in 2022-07, with the labels that each got.

#7 parser
  .vscode/configurationCache.log
  .vscode/dryrun.log
  .vscode/launch.json
  .vscode/settings.json
  .vscode/targets.log
  exemple.avm
  src/main.cpp
  src/parser/Parser.cpp
  src/parser/Parser.hpp
Labels: enhancement

#12 Archi
  Makefile
  src/IOperand.hpp
  src/exception/Exception.cpp
  src/exception/Exception.hpp
  src/factory/Factory.cpp
  src/factory/Factory.hpp
  src/types/BigDecimal.cpp
  src/types/BigDecimal.hpp
  src/types/Double.cpp
  src/types/Double.hpp
  src/types/Float.cpp
  src/types/Float.hpp
  src/types/Int16.cpp
  src/types/Int16.hpp
  src/types/Int32.cpp
  src/types/Int32.hpp
  src/types/Int8.cpp
  src/types/Int8.hpp
Labels: Factory

#13 Funtionnal Operand before stack management
  Makefile
  src/IOperand.hpp
  src/factory/Factory.cpp
  src/main.cpp
  src/memory/Memory.cpp
  src/memory/Memory.hpp
  src/types/BigDecimal.cpp
  src/types/BigDecimal.hpp
  src/types/Double.cpp
  src/types/Double.hpp
  src/types/Float.cpp
  src/types/Float.hpp
  src/types/Int16.cpp
  src/types/Int16.hpp
  src/types/Int32.cpp
  src/types/Int32.hpp
  src/types/Int8.cpp
  src/types/Int8.hpp
  src/types/Operand.cpp
  src/types/Operand.hpp
Labels: enhancement

#11 10 improve parser
  Makefile
  exemple.avm
  src/IOperand.hpp
  src/main.cpp
  src/memory/Memory.hpp
  src/parser/CommandData.cpp
  src/parser/CommandData.hpp
  src/parser/Interpretor.cpp
  src/parser/Interpretor.hpp
  src/parser/Parser.cpp
  src/parser/Parser.hpp
Labels: Parser

#24 fix assert condition
  src/memory/Memory.cpp
Labels: bug

#31 29 fix command comment
  src/memory/Memory.cpp
  src/parser/Parser.cpp
Labels: bug

#30 26 fix regex
  src/parser/Parser.cpp
Labels: bug

#33 fix setter for registre
  src/main.cpp
  src/parser/Interpretor.cpp
  src/parser/Interpretor.hpp
Labels: bug

#36 35 change set data for registre
  src/memory/Memory.cpp
  src/memory/Memory.hpp
  src/parser/Interpretor.cpp
  src/parser/Interpretor.hpp
Labels: enhancement

#42 fix comment in line
  src/parser/Parser.cpp
Labels: bug

#46 45 fix regex to accept for comment
  exemple.avm
  src/main.cpp
  src/memory/Memory.cpp
  src/parser/Interpretor.hpp
  src/parser/Parser.cpp
  src/types/Operand.cpp
Labels: bug

#48 47 fix regex to allow comment inline
  src/parser/Parser.cpp
  tests/exemple.avm
Labels: bug

#52 fix #51
  src/parser/Parser.cpp
Labels: bug, enhancement

#61 [NA]: fix mul
  src/types/Operand.cpp
  tests/mul.avm
  tests/testsParser.cpp
Labels: bug, enhancement

#62 58 exception in parser
  src/exception/Exception.cpp
  src/exception/Exception.hpp
  src/main.cpp
  src/parser/Parser.cpp
  tests/exemple.avm
  unit_tests
Labels: enhancement

#63 fix ';' in value & reading file
  src/parser/Parser.cpp
  tests/exemple.avm
Labels: bug, enhancement
